spring:
  application:
    name: fnmusic-user-mgmt
  profiles:
    active: dev

#eureka:
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka